// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage(flash string, next string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"robots\" content=\"noindex,nofollow\"><title>Sign in — Offbeat ChatFlow</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"\"><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\"><link rel=\"stylesheet\" href=\"/static/tokens.css\"><link rel=\"stylesheet\" href=\"/static/app.css\"><script src=\"https://unpkg.com/alpinejs@3.14.3/dist/cdn.min.js\" defer></script></head><body class=\"auth-page\"><div class=\"auth-card\"><div class=\"auth-logo\"><img src=\"/static/logo.png\" alt=\"Offbeat ChatFlow\" height=\"36\"></div><h1 class=\"auth-title\">Sign in</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if flash != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"login-err\" class=\"callout callout--danger\" role=\"alert\" aria-live=\"assertive\"><span aria-hidden=\"true\">⚠</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/auth_pages.templ`, Line: 27, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(flash)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/auth_pages.templ`, Line: 27, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"post\" action=\"/login\" class=\"auth-form\" x-data=\"{ showPwd: false, capslock: false, submitting: false }\" x-on:submit=\"submitting = true\"><input type=\"hidden\" name=\"next\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(next)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/auth_pages.templ`, Line: 37, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"> <label class=\"field\" for=\"login-email\"><span>Email</span> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if flash != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<input id=\"login-email\" type=\"email\" name=\"email\" required autofocus autocomplete=\"email\" aria-describedby=\"login-err\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<input id=\"login-email\" type=\"email\" name=\"email\" required autofocus autocomplete=\"email\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</label> <label class=\"field\" for=\"login-pwd\"><span>Password</span><div class=\"auth-pwd-wrapper\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if flash != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<input id=\"login-pwd\" type=\"password\" x-bind:type=\"showPwd ? 'text' : 'password'\" name=\"password\" required autocomplete=\"current-password\" x-on:keyup=\"capslock = $event.getModifierState('CapsLock')\" x-on:keydown=\"capslock = $event.getModifierState('CapsLock')\" aria-describedby=\"login-err\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<input id=\"login-pwd\" type=\"password\" x-bind:type=\"showPwd ? 'text' : 'password'\" name=\"password\" required autocomplete=\"current-password\" x-on:keyup=\"capslock = $event.getModifierState('CapsLock')\" x-on:keydown=\"capslock = $event.getModifierState('CapsLock')\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<button type=\"button\" class=\"auth-pwd-toggle\" x-on:click=\"showPwd = !showPwd\" x-bind:aria-pressed=\"showPwd.toString()\" x-bind:aria-label=\"showPwd ? 'Hide password' : 'Show password'\"><svg x-show=\"!showPwd\" viewBox=\"0 0 20 20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" width=\"18\" height=\"18\" aria-hidden=\"true\"><path d=\"M1 10s3.5-7 9-7 9 7 9 7-3.5 7-9 7-9-7-9-7z\"></path> <circle cx=\"10\" cy=\"10\" r=\"3\"></circle></svg> <svg x-show=\"showPwd\" x-cloak viewBox=\"0 0 20 20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" width=\"18\" height=\"18\" aria-hidden=\"true\"><path d=\"M1 10s3.5-7 9-7 9 7 9 7-3.5 7-9 7-9-7-9-7z\"></path> <circle cx=\"10\" cy=\"10\" r=\"3\"></circle> <line x1=\"2\" y1=\"2\" x2=\"18\" y2=\"18\" stroke-linecap=\"round\"></line></svg></button></div><span class=\"auth-caps-hint\" x-show=\"capslock\" x-cloak aria-live=\"polite\">⇪ Caps Lock is on</span></label> <button class=\"btn btn-primary\" type=\"submit\" x-bind:disabled=\"submitting\" x-bind:aria-busy=\"submitting.toString()\"><span x-show=\"!submitting\">Sign in</span> <span x-show=\"submitting\" x-cloak aria-hidden=\"true\">Signing in…</span></button></form><div class=\"auth-footer\"><span class=\"auth-forgot\">Forgot your password?</span> <span class=\"auth-help\">Contact your administrator to reset it.</span></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
