// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"whatsapptool/internal/db"
	mw "whatsapptool/internal/web/middleware"
)

// EditContactPage mirrors the New Contact form layout, pre-filled for editing.
func EditContactPage(agent *mw.AgentClaims, c *db.Contact, tags []db.Tag, currentTags []string, errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(ShellOpen(agent, "/contacts", "Edit Contact", "")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-wrap nc-pg\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(editContactXData(c, currentTags))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/edit_contact_page.templ`, Line: 12, Col: 71}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errMsg != "" {
			templ_7745c5c3_Err = templ.Raw(FormBanner(errMsg)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"nc-hd\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnGhost, BtnMd, fmt.Sprintf("/contacts/%s/view", c.ID), ncChevronLeftSVG, "", templ.Attributes{"aria-label": "Back to profile"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div><div class=\"screen-title\">Edit Contact</div><div class=\"screen-subtitle\">Update this contact's details</div></div></div><div class=\"nc-body\"><div class=\"card nc-form-card\"><form method=\"POST\" action=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.SafeURL
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/contacts/%s/update", c.ID)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/edit_contact_page.templ`, Line: 25, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><div class=\"nc-row\"><div class=\"form-group\"><label class=\"form-label\">Full name <span class=\"nc-req\">*</span></label> <input class=\"form-input\" type=\"text\" name=\"name\" x-model=\"name\" placeholder=\"Priya Sharma\" required autocomplete=\"off\"></div><div class=\"form-group\"><label class=\"form-label\">WhatsApp number <span class=\"nc-req\">*</span></label> <input class=\"form-input\" type=\"tel\" name=\"phone\" x-model=\"phone\" placeholder=\"+91 98765 43210\" required></div></div><div class=\"nc-row\"><div class=\"form-group\"><label class=\"form-label\">Email <span class=\"nc-opt\">(optional)</span></label> <input class=\"form-input\" type=\"email\" name=\"email\" x-model=\"email\" placeholder=\"priya@example.com\"></div><div class=\"form-group\"><label class=\"form-label\">City <span class=\"nc-opt\">(optional)</span></label> <select class=\"form-input\" name=\"city\" x-model=\"city\"><option value=\"\">Select city...</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, ct := range indianCities {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(ct)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/edit_contact_page.templ`, Line: 46, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(ct)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/edit_contact_page.templ`, Line: 46, Col: 34}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</select></div></div><div class=\"form-group\"><label class=\"form-label\">Tags <span class=\"nc-opt\">(optional)</span></label><div class=\"nc-tag-pills\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(tags) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<span style=\"color:var(--text-secondary);font-size:13px\">No tags yet — create tags in the contacts list first.</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, t := range tags {
			templ_7745c5c3_Err = TagPill(TagToggle, t.Name, TagColorDefault, false, templ.Attributes{
				":class": fmt.Sprintf("{'tag-pill--on':tags.includes('%s')}", jsStr(t.Name)),
				"@click": fmt.Sprintf("toggleTag('%s')", jsStr(t.Name)),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><input type=\"hidden\" name=\"tags\" :value=\"tags.join(',')\"></div><label class=\"nc-consent-row\"><div><div class=\"nc-consent-title\">Marketing consent</div><div class=\"nc-consent-desc\">Contact has opted in to receive WhatsApp messages</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Toggle("opt_in", c.OptedIn, templ.Attributes{"value": "on", "x-model": "optedIn"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</label><div class=\"form-group\" style=\"margin-top:20px\"><label class=\"form-label\">Add note <span class=\"nc-opt\">(optional)</span></label> <textarea class=\"form-input nc-notes\" name=\"notes\" placeholder=\"Add an internal note about this contact...\" rows=\"3\"></textarea></div><div class=\"nc-footer\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnSecondary, BtnMd, fmt.Sprintf("/contacts/%s/view", c.ID), "", "Cancel", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnPrimary, BtnMd, "", "", "Save changes", templ.Attributes{
			"type":      "submit",
			":disabled": "!name.trim() || phone.trim().length < 5",
			":class":    "{'btn-disabled':!name.trim() || phone.trim().length < 5}",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></form></div><div class=\"nc-preview-card\"><div class=\"nc-preview-label\">CONTACT PREVIEW</div><div class=\"nc-preview-body\"><div class=\"nc-preview-av\" x-text=\"initials\"></div><div><div class=\"nc-preview-name\" x-text=\"name.trim() || 'Full name'\"></div><div class=\"nc-preview-city\" x-text=\"city || 'City'\"></div></div></div><div class=\"nc-preview-phone\" x-text=\"phone || '+91'\"></div><div class=\"nc-preview-consent\"><span class=\"consent-dot\" :class=\"optedIn ? 'consent-dot--in' : 'consent-dot--out'\"></span> <span x-text=\"optedIn ? 'Opted in' : 'Opted out'\" :style=\"optedIn ? 'color:var(--accent)' : 'color:var(--danger)'\"></span></div></div></div><script>\n\t\tfunction ncEditApp(init) {\n\t\t  return {\n\t\t    name: init.name || '', phone: init.phone || '+91', email: init.email || '',\n\t\t    city: init.city || '', optedIn: !!init.optedIn, tags: init.tags || [],\n\t\t    get initials() {\n\t\t      const p = this.name.trim().split(/\\s+/).filter(Boolean);\n\t\t      if (!p.length) return '?';\n\t\t      let i = p[0].charAt(0);\n\t\t      if (p.length > 1) i += p[p.length-1].charAt(0);\n\t\t      return i.toUpperCase();\n\t\t    },\n\t\t    toggleTag(n) {\n\t\t      const i = this.tags.indexOf(n);\n\t\t      if (i >= 0) this.tags.splice(i,1); else this.tags.push(n);\n\t\t    }\n\t\t  };\n\t\t}\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(ShellClose()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
