package templates

// inbox_helpers.go — pure-Go helpers for the inbox template family.
// This file is NOT generated by templ; it survives every `templ generate` run.

import (
	"fmt"
	"html"
	"regexp"
	"strings"
	"time"

	"whatsapptool/internal/db"
	"whatsapptool/internal/whatsapp"
)

// WhatsApp text formatting markers.
var (
	waMono   = regexp.MustCompile("```([^`\n]+?)```")
	waBold   = regexp.MustCompile(`\*([^*\n]+?)\*`)
	waItalic = regexp.MustCompile(`_([^_\n]+?)_`)
	waStrike = regexp.MustCompile(`~([^~\n]+?)~`)
)

// formatWA renders WhatsApp text formatting (*bold*, _italic_, ~strike~,
// ```mono```) plus line breaks into safe HTML. The text is HTML-escaped first,
// so message content can never inject markup.
func formatWA(s string) string {
	s = html.EscapeString(s)
	s = waMono.ReplaceAllString(s, "<code>$1</code>")
	s = waBold.ReplaceAllString(s, "<strong>$1</strong>")
	s = waItalic.ReplaceAllString(s, "<em>$1</em>")
	s = waStrike.ReplaceAllString(s, "<del>$1</del>")
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

// messageBodyHTML is messageBody with WhatsApp formatting applied, as safe HTML.
func messageBodyHTML(msg *db.Message) string {
	return formatWA(messageBody(msg))
}

// winBadgeClass returns the 24h-window badge class based on urgency: green while
// there's plenty of time, amber under 2 hours, red once the window has closed.
func winBadgeClass(lastInboundAt *time.Time) string {
	if !whatsapp.IsWindowOpen(lastInboundAt) {
		return "win-badge win-closed"
	}
	if whatsapp.TimeUntilExpiry(lastInboundAt) < 2*time.Hour {
		return "win-badge win-soon"
	}
	return "win-badge win-open"
}

// ── SVG status-tick string constants ─────────────────────────────────────────
// Referenced by the msgStatus templ component (via @templ.Raw) and by
// msgStatusHTML (server-side render used after live WS status updates via JS).
// The read state uses stroke-width 2.6 vs 1.8 for delivered — a grayscale-safe
// distinguisher so shape+weight carry the cue, not color alone.

const (
	svgSent   = `<svg width="18" height="16" viewBox="0 0 18 16"><path class="tick" d="M3 8.5l3.5 3.5L14 4"/></svg>`
	svgDouble = `<svg width="22" height="16" viewBox="0 0 22 16"><path class="tick" d="M2 8.5l3.5 3.5L13 4"/><path class="tick" d="M8 8.5l3.5 3.5L19 4"/></svg>`
	svgQueued = `<svg width="16" height="16" viewBox="0 0 16 16"><circle class="ico" cx="8" cy="8" r="6"/><path class="ico" d="M8 4.6V8l2.4 1.6"/></svg>`
	svgFailed = `<svg width="16" height="16" viewBox="0 0 16 16"><circle class="ico" cx="8" cy="8" r="6"/><path class="ico" d="M8 5v3.5M8 10.6v.2"/></svg>`
)

// msgStatusHTML returns the full span+SVG string for server-rendered status.
// Must stay in sync with the msgStatusSVG JavaScript function in InboxPage.
func msgStatusHTML(status string) string {
	switch status {
	case "sent":
		return `<span class="stat stat--sent" role="img" aria-label="Sent">` + svgSent + `</span>`
	case "delivered":
		return `<span class="stat stat--delivered" role="img" aria-label="Delivered">` + svgDouble + `</span>`
	case "read":
		return `<span class="stat stat--read" role="img" aria-label="Read">` + svgDouble + `</span>`
	case "failed":
		return `<span class="stat stat--failed" role="img" aria-label="Failed to send">` + svgFailed + `</span>`
	default:
		return `<span class="stat stat--queued" role="img" aria-label="Queued">` + svgQueued + `</span>`
	}
}

// TickDataScript returns an inline <script> block that seeds the browser-side
// msgStatusSVG() function with the server-side SVG constants. Both the initial
// server render and live WebSocket status updates derive from the same strings,
// so SVG paths are defined exactly once (here) instead of twice.
func TickDataScript() string {
	return `<script id="tick-data">` +
		`var _tickSpan={` +
		`sent:` + tickQ(`<span class="stat stat--sent" role="img" aria-label="Sent">`+svgSent+`</span>`) + `,` +
		`delivered:` + tickQ(`<span class="stat stat--delivered" role="img" aria-label="Delivered">`+svgDouble+`</span>`) + `,` +
		`read:` + tickQ(`<span class="stat stat--read" role="img" aria-label="Read">`+svgDouble+`</span>`) + `,` +
		`failed:` + tickQ(`<span class="stat stat--failed" role="img" aria-label="Failed to send">`+svgFailed+`</span>`) + `,` +
		`queued:` + tickQ(`<span class="stat stat--queued" role="img" aria-label="Queued">`+svgQueued+`</span>`) +
		`};</script>`
}

// tickQ wraps s in a JS backtick template literal.
// Safe because the SVG constants contain no backtick characters.
func tickQ(s string) string { return "`" + s + "`" }

// ── Template helpers ──────────────────────────────────────────────────────────

func initial(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "?"
	}
	if strings.HasPrefix(name, "+") {
		r := []rune(name)
		if len(r) >= 3 {
			return string(r[len(r)-2:])
		}
		return "#"
	}
	r := []rune(name)
	return strings.ToUpper(string(r[0]))
}

// twoInitials returns up to two uppercase initials: "Priya Sharma"→"PS", "Govind"→"G", "+919812…"→last 2 digits.
func twoInitials(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "?"
	}
	if strings.HasPrefix(name, "+") {
		r := []rune(name)
		if len(r) >= 2 {
			return string(r[len(r)-2:])
		}
		return "#"
	}
	words := strings.Fields(name)
	if len(words) >= 2 {
		r0 := []rune(words[0])
		r1 := []rune(words[len(words)-1])
		if len(r0) > 0 && len(r1) > 0 {
			return strings.ToUpper(string(r0[0])) + strings.ToUpper(string(r1[0]))
		}
	}
	r := []rune(words[0])
	if len(r) > 0 {
		return strings.ToUpper(string(r[0]))
	}
	return "?"
}

var avatarPalette = []string{
	"av-purple", "av-blue", "av-green", "av-orange", "av-red",
	"av-teal", "av-pink", "av-indigo", "av-amber", "av-cyan",
}

// avatarColor returns a stable CSS class from the palette based on the contact name.
func avatarColor(name string) string {
	if name == "" {
		return "av-purple"
	}
	h := 0
	for _, c := range name {
		h = (h*31 + int(c)) % len(avatarPalette)
	}
	if h < 0 {
		h += len(avatarPalette)
	}
	return avatarPalette[h]
}

// shortDate formats a time as "02 Jan 2006" in IST.
func shortDate(t time.Time) string {
	return istFmt(t, "02 Jan 2006")
}

func shortTime(t *time.Time) string {
	if t == nil {
		return ""
	}
	ist := t.In(istLoc)
	now := time.Now().In(istLoc)
	if ist.Year() == now.Year() && ist.YearDay() == now.YearDay() {
		return ist.Format("15:04")
	}
	return ist.Format("02 Jan")
}

func shortTimestamp(t time.Time) string {
	return istFmt(t, "15:04")
}

func truncate(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

func bubbleClass(direction string) string {
	if direction == "inbound" {
		return "bub in"
	}
	return "bub out"
}

func messageBody(msg *db.Message) string {
	if msg.Content == nil {
		return ""
	}
	if body, ok := msg.Content["body"]; ok {
		if s, ok := body.(string); ok {
			return s
		}
	}
	if tmpl, ok := msg.Content["template"]; ok {
		if s, ok := tmpl.(string); ok && s != "" {
			return "[Template: " + s + "]"
		}
		return "[Template message]"
	}
	if msg.MediaPath != nil {
		return fmt.Sprintf("[%s]", msg.MessageType)
	}
	return ""
}

func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func composerPlaceholder(conv *db.Conversation) string {
	if whatsapp.IsWindowOpen(conv.LastInboundAt) {
		return "Type a message…"
	}
	return "Window closed — use Template button to send"
}
