package templates

// inbox_helpers.go — pure-Go helpers for the inbox template family.
// This file is NOT generated by templ; it survives every `templ generate` run.

import (
	"fmt"
	"strings"
	"time"

	"whatsapptool/internal/db"
	"whatsapptool/internal/whatsapp"
)

// ── SVG status-tick string constants ─────────────────────────────────────────
// Referenced by the msgStatus templ component (via @templ.Raw) and by
// msgStatusHTML (server-side render used after live WS status updates via JS).
// The read state uses stroke-width 2.6 vs 1.8 for delivered — a grayscale-safe
// distinguisher so shape+weight carry the cue, not color alone.

const (
	svgSent   = `<svg width="18" height="16" viewBox="0 0 18 16"><path class="tick" d="M3 8.5l3.5 3.5L14 4"/></svg>`
	svgDouble = `<svg width="22" height="16" viewBox="0 0 22 16"><path class="tick" d="M2 8.5l3.5 3.5L13 4"/><path class="tick" d="M8 8.5l3.5 3.5L19 4"/></svg>`
	svgQueued = `<svg width="16" height="16" viewBox="0 0 16 16"><circle class="ico" cx="8" cy="8" r="6"/><path class="ico" d="M8 4.6V8l2.4 1.6"/></svg>`
	svgFailed = `<svg width="16" height="16" viewBox="0 0 16 16"><circle class="ico" cx="8" cy="8" r="6"/><path class="ico" d="M8 5v3.5M8 10.6v.2"/></svg>`
)

// msgStatusHTML returns the full span+SVG string for server-rendered status.
// Must stay in sync with the msgStatusSVG JavaScript function in InboxPage.
func msgStatusHTML(status string) string {
	switch status {
	case "sent":
		return `<span class="stat stat--sent" role="img" aria-label="Sent">` + svgSent + `</span>`
	case "delivered":
		return `<span class="stat stat--delivered" role="img" aria-label="Delivered">` + svgDouble + `</span>`
	case "read":
		return `<span class="stat stat--read" role="img" aria-label="Read">` + svgDouble + `</span>`
	case "failed":
		return `<span class="stat stat--failed" role="img" aria-label="Failed to send">` + svgFailed + `</span>`
	default:
		return `<span class="stat stat--queued" role="img" aria-label="Queued">` + svgQueued + `</span>`
	}
}

// ── Template helpers ──────────────────────────────────────────────────────────

func initial(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "?"
	}
	if strings.HasPrefix(name, "+") {
		r := []rune(name)
		if len(r) >= 3 {
			return string(r[len(r)-2:])
		}
		return "#"
	}
	r := []rune(name)
	return strings.ToUpper(string(r[0]))
}

// twoInitials returns up to two uppercase initials: "Priya Sharma"→"PS", "Govind"→"G", "+919812…"→last 2 digits.
func twoInitials(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "?"
	}
	if strings.HasPrefix(name, "+") {
		r := []rune(name)
		if len(r) >= 2 {
			return string(r[len(r)-2:])
		}
		return "#"
	}
	words := strings.Fields(name)
	if len(words) >= 2 {
		r0 := []rune(words[0])
		r1 := []rune(words[len(words)-1])
		if len(r0) > 0 && len(r1) > 0 {
			return strings.ToUpper(string(r0[0])) + strings.ToUpper(string(r1[0]))
		}
	}
	r := []rune(words[0])
	if len(r) > 0 {
		return strings.ToUpper(string(r[0]))
	}
	return "?"
}

var avatarPalette = []string{
	"av-purple", "av-blue", "av-green", "av-orange", "av-red",
	"av-teal", "av-pink", "av-indigo", "av-amber", "av-cyan",
}

// avatarColor returns a stable CSS class from the palette based on the contact name.
func avatarColor(name string) string {
	if name == "" {
		return "av-purple"
	}
	h := 0
	for _, c := range name {
		h = (h*31 + int(c)) % len(avatarPalette)
	}
	if h < 0 {
		h += len(avatarPalette)
	}
	return avatarPalette[h]
}

// shortDate formats a time as "02 Jan 2006".
func shortDate(t time.Time) string {
	return t.Local().Format("02 Jan 2006")
}

func shortTime(t *time.Time) string {
	if t == nil {
		return ""
	}
	now := time.Now()
	if t.Year() == now.Year() && t.YearDay() == now.YearDay() {
		return t.Format("15:04")
	}
	return t.Format("02 Jan")
}

func shortTimestamp(t time.Time) string {
	return t.Local().Format("15:04")
}

func truncate(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

func bubbleClass(direction string) string {
	if direction == "inbound" {
		return "bub in"
	}
	return "bub out"
}

func messageBody(msg *db.Message) string {
	if msg.Content == nil {
		return ""
	}
	if body, ok := msg.Content["body"]; ok {
		if s, ok := body.(string); ok {
			return s
		}
	}
	if tmpl, ok := msg.Content["template"]; ok {
		if s, ok := tmpl.(string); ok && s != "" {
			return "[Template: " + s + "]"
		}
		return "[Template message]"
	}
	if msg.MediaPath != nil {
		return fmt.Sprintf("[%s]", msg.MessageType)
	}
	return ""
}

func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func composerPlaceholder(conv *db.Conversation) string {
	if whatsapp.IsWindowOpen(conv.LastInboundAt) {
		return "Type a message…"
	}
	return "Window closed — use Template button to send"
}
