// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"whatsapptool/internal/db"
	mw "whatsapptool/internal/web/middleware"
)

func NewContactPage(agent *mw.AgentClaims, tags []db.Tag, errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(ShellOpen(agent, "/contacts", "New Contact", "")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-wrap nc-pg\" x-data=\"ncApp()\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errMsg != "" {
			templ_7745c5c3_Err = templ.Raw(FormBanner(errMsg)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"nc-hd\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnGhost, BtnMd, "/contacts", ncChevronLeftSVG, "", templ.Attributes{"aria-label": "Back to contacts"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div><div class=\"screen-title\">New Contact</div><div class=\"screen-subtitle\">Add a contact to your directory</div></div></div><div class=\"nc-body\"><div class=\"card nc-form-card\"><form method=\"POST\" action=\"/contacts/new\" x-ref=\"ncForm\" @submit.prevent=\"flushAndSubmit()\"><div class=\"nc-row\"><div class=\"form-group\"><label class=\"form-label\">Full name <span class=\"nc-req\">*</span></label> <input class=\"form-input\" type=\"text\" name=\"name\" x-model=\"name\" placeholder=\"Priya Sharma\" required autocomplete=\"off\"></div><div class=\"form-group\"><label class=\"form-label\">WhatsApp number <span class=\"nc-req\">*</span></label> <input class=\"form-input\" type=\"tel\" name=\"phone\" x-model=\"phone\" placeholder=\"+91 98765 43210\" required></div></div><div class=\"nc-row\"><div class=\"form-group\"><label class=\"form-label\">Email <span class=\"nc-opt\">(optional)</span></label> <input class=\"form-input\" type=\"email\" name=\"email\" placeholder=\"priya@example.com\"></div><div class=\"form-group\"><label class=\"form-label\">City <span class=\"nc-opt\">(optional)</span></label> <select class=\"form-input\" name=\"city\" x-model=\"city\"><option value=\"\">Select city...</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, c := range indianCities {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(c)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/new_contact_page.templ`, Line: 45, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(c)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/new_contact_page.templ`, Line: 45, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</select></div></div><div class=\"form-group\"><label class=\"form-label\">Tags <span class=\"nc-opt\">(optional)</span></label><!-- Selected tags (existing + custom) as removable chips --><div class=\"nc-tag-pills\" style=\"margin-bottom:8px\"><template x-for=\"t in tags\" :key=\"t\"><span class=\"tag-pill tag-pill--on\" style=\"display:inline-flex;align-items:center;gap:5px\"><span x-text=\"t\"></span> <button type=\"button\" @click=\"removeTag(t)\" aria-label=\"Remove tag\" style=\"border:none;background:none;cursor:pointer;font-size:15px;line-height:1;color:inherit\">&times;</button></span></template><span x-show=\"tags.length===0\" style=\"color:var(--text-secondary);font-size:13px\">No tags selected</span></div><!-- Type a custom tag and press Enter to add it (created automatically on save) --><input class=\"form-input\" type=\"text\" x-model=\"tagInput\" placeholder=\"Type a new tag and press Enter — e.g. Technology, Real Estate\" @keydown.enter.prevent=\"addTag(tagInput); tagInput=''\" autocomplete=\"off\"><div style=\"font-size:12px;color:var(--text-secondary);margin-top:4px\">A tag that doesn't exist yet is created automatically.</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(tags) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"nc-tag-pills\" style=\"margin-top:8px\"><span style=\"color:var(--text-secondary);font-size:12px;width:100%\">Quick-pick existing:</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, t := range tags {
				templ_7745c5c3_Err = TagPill(TagToggle, t.Name, TagColorDefault, false, templ.Attributes{
					":class": fmt.Sprintf("{'tag-pill--on':tags.includes('%s')}", jsStr(t.Name)),
					"@click": fmt.Sprintf("toggleTag('%s')", jsStr(t.Name)),
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<input type=\"hidden\" name=\"tags\" :value=\"tags.join(',')\"></div><label class=\"nc-consent-row\"><div><div class=\"nc-consent-title\">Marketing consent</div><div class=\"nc-consent-desc\">Contact has opted in to receive WhatsApp messages</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Toggle("opt_in", true, templ.Attributes{"value": "on", "x-model": "optedIn"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</label><div class=\"form-group\" style=\"margin-top:20px\"><label class=\"form-label\">Notes <span class=\"nc-opt\">(optional)</span></label> <textarea class=\"form-input nc-notes\" name=\"notes\" placeholder=\"Internal notes about this contact...\" rows=\"4\"></textarea></div><div class=\"nc-footer\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnSecondary, BtnMd, "/contacts", "", "Cancel", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(BtnPrimary, BtnMd, "", "", "Save contact", templ.Attributes{
			"type":      "submit",
			":disabled": "!name.trim() || phone.trim().length < 5",
			":class":    "{'btn-disabled':!name.trim() || phone.trim().length < 5}",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></form></div><div class=\"nc-preview-card\"><div class=\"nc-preview-label\">CONTACT PREVIEW</div><div class=\"nc-preview-body\"><div class=\"nc-preview-av\" x-text=\"initials\"></div><div><div class=\"nc-preview-name\" x-text=\"name.trim() || 'Full name'\"></div><div class=\"nc-preview-city\" x-text=\"city || 'City'\"></div></div></div><div class=\"nc-preview-phone\" x-text=\"phone || '+91'\"></div><div class=\"nc-preview-consent\"><span class=\"consent-dot\" :class=\"optedIn ? 'consent-dot--in' : 'consent-dot--out'\"></span> <span x-text=\"optedIn ? 'Opted in' : 'Opted out'\" :style=\"optedIn ? 'color:var(--accent)' : 'color:var(--danger)'\"></span></div></div></div></div><script>\n\tfunction ncApp() {\n\t  return {\n\t    name: '',\n\t    phone: '+91',\n\t    city: '',\n\t    optedIn: true,\n\t    tags: [],\n\t    tagInput: '',\n\t    get initials() {\n\t      const p = this.name.trim().split(/\\s+/).filter(Boolean);\n\t      if (!p.length) return '?';\n\t      let i = p[0].charAt(0);\n\t      if (p.length > 1) i += p[p.length-1].charAt(0);\n\t      return i.toUpperCase();\n\t    },\n\t    toggleTag(n) {\n\t      const i = this.tags.indexOf(n);\n\t      if (i >= 0) this.tags.splice(i,1); else this.tags.push(n);\n\t    },\n\t    addTag(raw) {\n\t      const n = (raw || '').trim().replace(/,+$/, '').trim();\n\t      if (n && !this.tags.some(t => t.toLowerCase() === n.toLowerCase())) this.tags.push(n);\n\t    },\n\t    removeTag(n) {\n\t      this.tags = this.tags.filter(t => t !== n);\n\t    },\n\t    flushAndSubmit() {\n\t      // Capture any tag still typed in the box (user clicked Save without Enter),\n\t      // then submit once Alpine has updated the hidden tags field.\n\t      if (this.tagInput.trim()) { this.addTag(this.tagInput); this.tagInput = ''; }\n\t      this.$nextTick(() => this.$refs.ncForm.submit());\n\t    }\n\t  };\n\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(ShellClose()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
